"use client"

import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "./Provider";
import { ClerkProvider } from "@clerk/nextjs";
import React, { useEffect, useState } from "react";
import UserLocationContext from "./context/UserLocationContext";

const inter = Inter({ subsets: ["latin"] });

//export const metadata = {
  //title: "CSU Rent-A-Bike",
  //description: "Generated by create next app",
//};

export default function RootLayout({ children }) {
  const [userLocation,setUserLocation]=useState([]);
  useEffect(()=>{
    getUserLocation();
  },[])
  const getUserLocation=()=>{
    navigator.geolocation.getCurrentPosition(function(pos){
      console.log(pos)
      setUserLocation({
        lat:pos.coords.latitude,
        lng:pos.coords.longitude
      })
      })
    
  }

  return (
    <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <UserLocationContext.Provider value={{userLocation,setUserLocation}}>
          {children}
          </UserLocationContext.Provider>
        </Provider>
          </body>
    </html>
    </ClerkProvider>
  );
}
